# Generated by Django 4.2.11 on 2024-04-23 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_charge_crime_evidence_investigation_student_suspect_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
