# Generated by Django 4.2.11 on 2024-04-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='email',
            field=models.EmailField(default='noelronnie050@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
