# Generated by Django 4.2.11 on 2024-04-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_crime_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='email',
        ),
    ]
