# Generated by Django 4.2.11 on 2024-04-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_crime_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
