# Generated by Django 4.2.11 on 2024-05-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_crime_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect',
            name='gender',
            field=models.TextField(blank=True),
        ),
    ]
